trigger:
  batch: true
  branches:
    include:
      - master

pr: none

steps:
  - task: AzureCLI@2
    displayName: 'Create function app'
    inputs:
      azureSubscription: "33a292c8-ddfa-4d96-af29-2329272c7338"
      scriptType: pscore
      scriptLocation: scriptPath
      scriptPath: $(System.DefaultWorkingDirectory)/powershell/Create-FunctionApp.ps1
      # arguments: >-
      #   -resourceGroup '${{ parameters.resourceGroup }}'
      #   -webAppIdt '${{ parameters.webAppIdt }}'
      #   -webAppPrf '${{ parameters.webAppPrf }}'
      #   -webAppRec '${{ parameters.webAppRec }}'
      #   -webAppVls '${{ parameters.webAppVls }}'
      #   -buildAgentIpAddress '$(buildAgent.IpAddress)'
      #   -defaultWorkingDirectory '$(System.DefaultWorkingDirectory)'